### ISSUE TITLE
Assignments without "new" break strings

### ISSUE THREAD

**Issue by danielbrauer** [wintermi/csharp-tmbundle#13]
String literals aren't properly recognized in assignments without "new".

This one was easy to demo because GitHub's C# syntax highlighting had the same issue:

``` csharp
class A {
    t = new B("a a");
    these = things;
    are = not;
    a = string;
}
class B {
    t = B("a a");
    these = things;
    are = not;
    a = string;
}
```

**Comment by danielbrauer** [comment]
This was fixed by https://github.com/atom/language-csharp/commit/3ddd53a6971dfc59e05f4eafb6b82f92f91db353

I've opened a PR with the same patch: https://github.com/wintermi/csharp-tmbundle/pull/14

**Comment by wintermi** [comment]
Pull request merged and issue now closed
